/**
 * ResultsDisplay Component
 * Displays ranked suspicious lines with export functionality
 */

import React, { useState } from 'react';
import jsPDF from 'jspdf';

function ResultsDisplay({ results, onReset }) {
  const [selectedLine, setSelectedLine] = useState(null);
  const [filterThreshold, setFilterThreshold] = useState(0);

  // Filter lines based on probability threshold
  const filteredLines = results.ranked_lines.filter(
    (line) => line.probability >= filterThreshold
  );

  // Get severity color based on probability
  const getSeverityColor = (probability) => {
    if (probability >= 0.8) return 'bg-red-100 border-red-500 text-red-900';
    if (probability >= 0.6) return 'bg-orange-100 border-orange-500 text-orange-900';
    if (probability >= 0.4) return 'bg-yellow-100 border-yellow-500 text-yellow-900';
    return 'bg-blue-100 border-blue-500 text-blue-900';
  };

  const getSeverityBadge = (probability) => {
    if (probability >= 0.8) return { label: 'Critical', color: 'bg-red-500' };
    if (probability >= 0.6) return { label: 'High', color: 'bg-orange-500' };
    if (probability >= 0.4) return { label: 'Medium', color: 'bg-yellow-500' };
    return { label: 'Low', color: 'bg-blue-500' };
  };

  // Export to CSV
  const exportToCSV = () => {
    const headers = ['Rank', 'File', 'Line', 'Probability', 'Code'];
    const rows = filteredLines.map((line) => [
      line.rank,
      line.file,
      line.line_number,
      line.probability.toFixed(4),
      `"${line.code.replace(/"/g, '""')}"`, // Escape quotes in code
    ]);

    const csvContent =
      [headers.join(',')]
        .concat(rows.map((row) => row.join(',')))
        .join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `fault_localization_${results.prediction_id.slice(0, 8)}.csv`;
    link.click();
    window.URL.revokeObjectURL(url);
  };

  // Export to PDF
  const exportToPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    let yPosition = margin;

    // Title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Fault Localization Report', margin, yPosition);
    yPosition += 10;

    // Metadata
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Repository: ${results.repository_path}`, margin, yPosition);
    yPosition += 6;
    doc.text(`Test: ${results.failing_test}`, margin, yPosition);
    yPosition += 6;
    doc.text(`Date: ${new Date(results.timestamp).toLocaleString()}`, margin, yPosition);
    yPosition += 6;
    doc.text(`Total Candidates: ${results.total_candidates}`, margin, yPosition);
    yPosition += 12;

    // Table header
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Ranked Suspicious Lines', margin, yPosition);
    yPosition += 8;

    // Lines
    doc.setFontSize(9);
    filteredLines.slice(0, 20).forEach((line, index) => {
      // Check if we need a new page
      if (yPosition > pageHeight - 30) {
        doc.addPage();
        yPosition = margin;
      }

      const severity = getSeverityBadge(line.probability);
      
      doc.setFont('helvetica', 'bold');
      doc.text(`#${line.rank} [${severity.label}]`, margin, yPosition);
      
      doc.setFont('helvetica', 'normal');
      doc.text(`Probability: ${(line.probability * 100).toFixed(1)}%`, margin + 40, yPosition);
      yPosition += 5;
      
      doc.setFontSize(8);
      doc.text(`${line.file}:${line.line_number}`, margin + 5, yPosition);
      yPosition += 4;
      
      // Code (truncate if too long)
      const codeText = line.code.length > 80 ? line.code.slice(0, 80) + '...' : line.code;
      doc.setFont('courier', 'normal');
      doc.text(codeText, margin + 5, yPosition);
      yPosition += 8;
      
      doc.setFontSize(9);
    });

    // Footer
    doc.setFontSize(8);
    doc.text(
      'Generated by AI Fault Localization Tool',
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );

    doc.save(`fault_report_${results.prediction_id.slice(0, 8)}.pdf`);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white rounded-xl shadow-lg p-6">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold text-gray-900">
              Analysis Results
            </h2>
            <p className="text-sm text-gray-600 mt-2">
              Found {results.total_candidates} suspicious lines in{' '}
              <code className="bg-gray-100 px-2 py-1 rounded text-xs">
                {results.repository_path}
              </code>
            </p>
            <p className="text-xs text-gray-500 mt-1">
              Test: <span className="font-mono">{results.failing_test}</span> |
              Analysis ID: {results.prediction_id.slice(0, 8)}...
            </p>
          </div>
          <button
            onClick={onReset}
            className="px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg font-medium transition"
          >
            New Analysis
          </button>
        </div>

        {/* Actions Bar */}
        <div className="mt-6 flex items-center justify-between border-t pt-4">
          <div className="flex items-center space-x-4">
            <div>
              <label className="text-sm text-gray-700 mr-2">
                Filter by probability ≥ {filterThreshold.toFixed(2)}
              </label>
              <input
                type="range"
                min="0"
                max="1"
                step="0.1"
                value={filterThreshold}
                onChange={(e) => setFilterThreshold(parseFloat(e.target.value))}
                className="w-40"
              />
            </div>
            <span className="text-sm text-gray-600">
              Showing {filteredLines.length} of {results.total_candidates} lines
            </span>
          </div>
          <div className="flex space-x-3">
            <button
              onClick={exportToCSV}
              className="px-4 py-2 bg-green-500 hover:bg-green-600 text-white rounded-lg font-medium transition flex items-center space-x-2"
            >
              <svg
                className="w-4 h-4"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                />
              </svg>
              <span>Export CSV</span>
            </button>
            <button
              onClick={exportToPDF}
              className="px-4 py-2 bg-red-500 hover:bg-red-600 text-white rounded-lg font-medium transition flex items-center space-x-2"
            >
              <svg
                className="w-4 h-4"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"
                />
              </svg>
              <span>Export PDF</span>
            </button>
          </div>
        </div>
      </div>

      {/* Results List */}
      <div className="space-y-3">
        {filteredLines.length === 0 ? (
          <div className="bg-white rounded-xl shadow-lg p-12 text-center">
            <svg
              className="w-16 h-16 text-gray-400 mx-auto mb-4"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            <p className="text-gray-600">
              No lines match the current filter threshold
            </p>
          </div>
        ) : (
          filteredLines.map((line) => {
            const severity = getSeverityBadge(line.probability);
            const isSelected = selectedLine === line.rank;

            return (
              <div
                key={line.rank}
                className={`bg-white rounded-xl shadow-md border-l-4 transition-all cursor-pointer hover:shadow-lg ${
                  getSeverityColor(line.probability)
                } ${isSelected ? 'ring-2 ring-blue-500' : ''}`}
                onClick={() => setSelectedLine(isSelected ? null : line.rank)}
              >
                <div className="p-5">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center space-x-3 mb-2">
                        <span className="text-2xl font-bold">#{line.rank}</span>
                        <span
                          className={`px-3 py-1 rounded-full text-xs font-semibold text-white ${severity.color}`}
                        >
                          {severity.label}
                        </span>
                        <div className="flex-1 bg-gray-200 rounded-full h-2 overflow-hidden">
                          <div
                            className={`h-full ${severity.color}`}
                            style={{ width: `${line.probability * 100}%` }}
                          />
                        </div>
                        <span className="text-sm font-bold">
                          {(line.probability * 100).toFixed(1)}%
                        </span>
                      </div>
                      <div className="flex items-center text-sm text-gray-600 space-x-2 mb-3">
                        <svg
                          className="w-4 h-4"
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth={2}
                            d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"
                          />
                        </svg>
                        <span className="font-mono">{line.file}</span>
                        <span>:</span>
                        <span className="font-bold">{line.line_number}</span>
                      </div>
                      <div className="bg-gray-50 rounded-lg p-3 font-mono text-sm border border-gray-200">
                        <code>{line.code}</code>
                      </div>
                    </div>
                  </div>

                  {/* Expandable Details */}
                  {isSelected && line.features && (
                    <div className="mt-4 pt-4 border-t border-gray-200">
                      <h4 className="text-sm font-semibold text-gray-700 mb-2">
                        Feature Details:
                      </h4>
                      <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                        {Object.entries(line.features).map(([key, value]) => (
                          <div
                            key={key}
                            className="bg-white border border-gray-200 rounded-lg p-2"
                          >
                            <p className="text-xs text-gray-500 capitalize">
                              {key.replace(/_/g, ' ')}
                            </p>
                            <p className="text-sm font-semibold text-gray-900">
                              {typeof value === 'number'
                                ? value.toFixed(3)
                                : value}
                            </p>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            );
          })
        )}
      </div>

      {/* Statistics Summary */}
      <div className="bg-white rounded-xl shadow-lg p-6">
        <h3 className="text-lg font-bold text-gray-900 mb-4">
          Statistics Summary
        </h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="text-center">
            <p className="text-3xl font-bold text-red-600">
              {filteredLines.filter((l) => l.probability >= 0.8).length}
            </p>
            <p className="text-sm text-gray-600 mt-1">Critical</p>
          </div>
          <div className="text-center">
            <p className="text-3xl font-bold text-orange-600">
              {
                filteredLines.filter(
                  (l) => l.probability >= 0.6 && l.probability < 0.8
                ).length
              }
            </p>
            <p className="text-sm text-gray-600 mt-1">High</p>
          </div>
          <div className="text-center">
            <p className="text-3xl font-bold text-yellow-600">
              {
                filteredLines.filter(
                  (l) => l.probability >= 0.4 && l.probability < 0.6
                ).length
              }
            </p>
            <p className="text-sm text-gray-600 mt-1">Medium</p>
          </div>
          <div className="text-center">
            <p className="text-3xl font-bold text-blue-600">
              {filteredLines.filter((l) => l.probability < 0.4).length}
            </p>
            <p className="text-sm text-gray-600 mt-1">Low</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ResultsDisplay;
